declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.gif'

declare module 'react-transition-group'
declare module 'rc-switch'
declare module 'intl'
declare module 'react-dropdown-select'
declare module 'styled-components'
declare module 'moment-duration-format'