---
# Define Docker Compose version.
version: "3"

# Define all the containers.
services:
  # API documenation container.
  api-documentation:
    build: ./app/backend/docs
    volumes:
      - ./app/backend/docs:/usr/src/docs
    ports:
      - 1338:4567
    command:  bash -c "cd ./docs && bundle install && bundle exec middleman server"
  # Backend Container.
  backend:
    expose:
      - 3001
  # Frontend Container.
  frontend:
    expose:
      - 3000
  # Maildev container.
  maildev:
    image: djfarrelly/maildev:latest
    expose:
      - 3002
    ports:
      - 1339:3003
    command:  bin/maildev --web 3003 --smtp 3002 -v
  # Nginx Container.
  nginx:
    build: ./nginx
    depends_on:
    - backend
    - frontend
    ports:
    - 1337:80
  # Nosqlclient client container.
  nosqlclient-client:
    image: mongoclient/mongoclient:latest
    depends_on:
     - mongo
    ports:
      - 1340:3000
