---
# Define Docker Compose version.
version: "3"

# Define all the containers.
services:
  # Backend Container.
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.development
    volumes:
      - ./app/backend:/usr/src/app
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: development
    command: /usr/src/app/bin/development-entrypoint.sh
  # Frontend Container.
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.development
    volumes:
      - ./app/frontend:/usr/src/app
    environment:
      NODE_ENV: development
    command: /usr/src/app/bin/development-entrypoint.sh
  # Mongo Container.
  mongo:
    image: mongo:4
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: SponteousDevManager
      MONGO_INITDB_ROOT_PASSWORD: GZiV12OmdDmmxkX2
  # Redis Container.
  redis:
    image: redis:3
    volumes:
      - redis-data:/data
    expose:
      - 6379

# Define all the external volumes.
volumes:
  mongo-data: ~
  redis-data: ~
